name: Validation Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-quality-validation:
    name: Code Quality Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check black
        run: |
          black --check .

      - name: Check isort
        run: |
          isort --check-only .

      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          PYTHONPATH=. pytest --cov=app --cov=tests --cov-report=term-missing tests/
